name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t my-node-app .
    - name: Push the Docker image to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: docker tag my-node-app ${{ secrets.DOCKER_USERNAME }}/my-node-app
    - run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "== Verificando Docker =="
          if ! command -v docker &> /dev/null; then
            echo "Docker no está instalado. Instalando..."
            if command -v apt &> /dev/null; then
              # Ubuntu/Debian
              sudo apt update -y
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ubuntu || true
            elif command -v yum &> /dev/null; then
              # Amazon Linux/CentOS
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user || true
            else
              echo "No se encontró apt ni yum. Aborto."
              exit 1
            fi
            echo "Docker instalado."
          else
            echo "Docker ya está instalado: $(docker --version)"
          fi
    
          echo "== Desplegando contenedor =="
          # Usa sudo para evitar problemas de permisos en la misma sesión SSH
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app
          sudo docker stop my-node-app || true
          sudo docker rm my-node-app || true
          sudo docker run -d -p 3000:3000 --name my-node-app ${{ secrets.DOCKER_USERNAME }}/my-node-app
    
          echo "== Contenedores en ejecución =="
          sudo docker ps
    